[package]
name = "orbit-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
orbit-fountain = { path = "../orbit-fountain" }
wasm-bindgen = "0.2"
getrandom = { version = "0.2", features = ["js"] }
js-sys = "0.3"

[dev-dependencies]
wasm-bindgen-test = "0.3"